# This is a basic workflow to help you get started with Actions

name: e2e

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Test
        env:
          E2EHubConnectionString: ${{secrets.E2EHubConnectionString}}
          TestHubName: ${{secrets.TestHubName}} 
        run: echo "${{ secrets.TestHubName }}"

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az iot hub device-twin list --login "${{ secrets.E2EHubConnectionString }}"