name: e2e
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: IoTHubTest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        shell: bash
        env:
          E2EHubConnectionString: ${{secrets.E2EHubConnectionString}}
          TestHubName: ${{secrets.TestHubName}} 
        run: echo "$TestHubName"

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az iot hub device-identity create -d e2edevice --login "${{ secrets.E2EHubConnectionString }}"
            echo e2eDevConnString=$(az iot hub device-identity connection-string show -d e2edevice --login "${{ secrets.E2EHubConnectionString }}" --query connectionString | tr -d '"') >> $GITHUB_ENV

      - name: Run Device
        run: docker run --rm -e ConnectionStrings__cs="${{ env.e2eDevConnString }}" ghcr.io/iotmodels/memmon:x64

      - name: InvokeCommand
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az iot hub invoke-device-method -d e2edevice --method-name getRuntimeStats --method-payload '2'--login "${{ secrets.E2EHubConnectionString }}"
            az iot hub device-identity delete -d e2edevice --login "${{ secrets.E2EHubConnectionString }}"